import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Footer from "@/components/Footer/Footer"
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider"
import Header from "@/components/Header/Header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "NextJS Store",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ReduxProvider>
					<Header />
					<main className="spacer">{children}</main>
				</ReduxProvider>
				<Footer />
				<div id="react-portals"></div>
			</body>
		</html>
	)
}
