import Breadcrumb from "@/components/UI/Breadcrumb/Breadcrumb"
import ProductsCategory from "@/components/Products/ProductsCategory/ProductsCategory"
import FilteredCategory from "@/components/Products/FilteredCategory/FilteredCategory"
import classes from "./[products]/Products.module.css"
import type { Metadata } from "next"

export const metadata: Metadata = {
	title: "Products",
	description: "Generated by create next app",
}

export default function ProductLayaout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<>
			<Breadcrumb />
			<ProductsCategory />
			<FilteredCategory />
			<section className={classes.section}>{children}</section>
		</>
	)
}
